import type { HeaderPerson } from "@/app/(dashboard)/_header/header-types";
import type { ConversationRow } from "./conversations-types";

export const conversationSellerPeople: HeaderPerson[] = [
  {
    name: "Julien Newman",
    avatar: "/avatars/aditya.jpg",
  },
  {
    name: "Yash Patel",
    avatar: "/avatars/yash.webp",
  },
];

export const conversationRows: ConversationRow[] = [
  {
    id: "northwind-health-maya-rodriguez",
    cardNumber: 87,
    probability: 35,
    contact: "Maya Rodriguez",
    deal: "Caterpillar deal",
    owner: "Julien Newman",
    ownerAvatar: "/avatars/aditya.jpg",
    stage: "Negotiation",
    lastUpdate: "2h ago",
  },
  {
    id: "aperture-labs-nolan-pierce",
    cardNumber: 65,
    probability: 55,
    contact: "Nolan Pierce",
    deal: "Sherwin-Williams deal",
    owner: "Yash Patel",
    ownerAvatar: "/avatars/yash.webp",
    stage: "Proposal",
    lastUpdate: "Yesterday",
  },
  {
    id: "bluebird-logistics-leah-kim",
    cardNumber: 42,
    probability: 20,
    contact: "Leah Kim",
    deal: "Whirlpool deal",
    owner: "Julien Newman",
    ownerAvatar: "/avatars/aditya.jpg",
    stage: "Discovery",
    lastUpdate: "Yesterday",
  },
  {
    id: "helix-financial-priya-nanda",
    cardNumber: 31,
    probability: 100,
    contact: "Priya Nanda",
    deal: "John Deere deal",
    owner: "Yash Patel",
    ownerAvatar: "/avatars/yash.webp",
    stage: "Closed won",
    lastUpdate: "3d ago",
  },
  {
    id: "greenline-energy-olivia-chen",
    cardNumber: 74,
    probability: 25,
    contact: "Olivia Chen",
    deal: "3M deal",
    owner: "Julien Newman",
    ownerAvatar: "/avatars/aditya.jpg",
    stage: "Discovery",
    lastUpdate: "5h ago",
  },
  {
    id: "stonegate-retail-ethan-ross",
    cardNumber: 76,
    probability: 45,
    contact: "Ethan Ross",
    deal: "General Mills deal",
    owner: "Yash Patel",
    ownerAvatar: "/avatars/yash.webp",
    stage: "Proposal",
    lastUpdate: "1d ago",
  },
  {
    id: "atlas-biotech-sofia-mendez",
    cardNumber: 78,
    probability: 70,
    contact: "Sofia Mendez",
    deal: "Tyson Foods deal",
    owner: "Yash Patel",
    ownerAvatar: "/avatars/yash.webp",
    stage: "Negotiation",
    lastUpdate: "4h ago",
  },
  {
    id: "harbor-insurance-liam-brooks",
    cardNumber: 80,
    probability: 50,
    contact: "Liam Brooks",
    deal: "Kroger deal",
    owner: "Julien Newman",
    ownerAvatar: "/avatars/aditya.jpg",
    stage: "Proposal",
    lastUpdate: "2d ago",
  },
  {
    id: "nova-manufacturing-zoe-patel",
    cardNumber: 82,
    probability: 30,
    contact: "Zoe Patel",
    deal: "Costco deal",
    owner: "Yash Patel",
    ownerAvatar: "/avatars/yash.webp",
    stage: "Discovery",
    lastUpdate: "6h ago",
  },
  {
    id: "cedar-logistics-jason-lee",
    cardNumber: 84,
    probability: 65,
    contact: "Jason Lee",
    deal: "Marriott deal",
    owner: "Yash Patel",
    ownerAvatar: "/avatars/yash.webp",
    stage: "Negotiation",
    lastUpdate: "8h ago",
  },
  {
    id: "brightpath-education-emma-davis",
    cardNumber: 86,
    probability: 0,
    contact: "Emma Davis",
    deal: "Hilton deal",
    owner: "Julien Newman",
    ownerAvatar: "/avatars/aditya.jpg",
    stage: "Closed lost",
    lastUpdate: "1w ago",
  },
  {
    id: "pinnacle-medical-marcus-ford",
    cardNumber: 88,
    probability: 100,
    contact: "Marcus Ford",
    deal: "Delta Air Lines deal",
    owner: "Yash Patel",
    ownerAvatar: "/avatars/yash.webp",
    stage: "Closed won",
    lastUpdate: "4d ago",
  },
  {
    id: "summit-payments-ava-morgan",
    cardNumber: 90,
    probability: 75,
    contact: "Ava Morgan",
    deal: "Southwest Airlines deal",
    owner: "Yash Patel",
    ownerAvatar: "/avatars/yash.webp",
    stage: "Negotiation",
    lastUpdate: "3h ago",
  },
  {
    id: "orion-telecom-noah-bennett",
    cardNumber: 92,
    probability: 60,
    contact: "Noah Bennett",
    deal: "FedEx deal",
    owner: "Julien Newman",
    ownerAvatar: "/avatars/aditya.jpg",
    stage: "Proposal",
    lastUpdate: "Yesterday",
  },
];
