import type { HeaderPerson } from "@/components/canvas/canvas-types";
import type { ConversationRow } from "./conversations-types";

export const conversationSellerPeople: HeaderPerson[] = [
  {
    name: "Aditya Newman",
    avatar: "/avatars/aditya.jpg",
  },
  {
    name: "Yash Patel",
    avatar: "/avatars/yash.webp",
  },
];

export const conversationRows: ConversationRow[] = [
  {
    id: "northwind-health-maya-rodriguez",
    cardNumber: 87,
    company: "Northwind Health",
    contact: "Maya Rodriguez",
    topic: "Security review + legal timeline",
    owner: "Aditya Newman",
    ownerAvatar: "/avatars/aditya.jpg",
    stage: "Negotiation",
    lastUpdate: "2h ago",
  },
  {
    id: "aperture-labs-nolan-pierce",
    cardNumber: 65,
    company: "Aperture Labs",
    contact: "Nolan Pierce",
    topic: "Procurement checklist and pricing",
    owner: "Yash Patel",
    ownerAvatar: "/avatars/yash.webp",
    stage: "Proposal",
    lastUpdate: "Yesterday",
  },
  {
    id: "bluebird-logistics-leah-kim",
    cardNumber: 42,
    company: "Bluebird Logistics",
    contact: "Leah Kim",
    topic: "Pilot scope confirmation",
    owner: "Aditya Newman",
    ownerAvatar: "/avatars/aditya.jpg",
    stage: "Discovery",
    lastUpdate: "Yesterday",
  },
  {
    id: "helix-financial-priya-nanda",
    cardNumber: 31,
    company: "Helix Financial",
    contact: "Priya Nanda",
    topic: "Final redlines and signature",
    owner: "Yash Patel",
    ownerAvatar: "/avatars/yash.webp",
    stage: "Closed won",
    lastUpdate: "3d ago",
  },
  {
    id: "greenline-energy-olivia-chen",
    cardNumber: 74,
    company: "Greenline Energy",
    contact: "Olivia Chen",
    topic: "Energy compliance and deployment scope",
    owner: "Aditya Newman",
    ownerAvatar: "/avatars/aditya.jpg",
    stage: "Discovery",
    lastUpdate: "5h ago",
  },
  {
    id: "stonegate-retail-ethan-ross",
    cardNumber: 76,
    company: "Stonegate Retail",
    contact: "Ethan Ross",
    topic: "Pricing tiers and pilot locations",
    owner: "Yash Patel",
    ownerAvatar: "/avatars/yash.webp",
    stage: "Proposal",
    lastUpdate: "1d ago",
  },
  {
    id: "atlas-biotech-sofia-mendez",
    cardNumber: 78,
    company: "Atlas Biotech",
    contact: "Sofia Mendez",
    topic: "Security questionnaire follow-up",
    owner: "Yash Patel",
    ownerAvatar: "/avatars/yash.webp",
    stage: "Negotiation",
    lastUpdate: "4h ago",
  },
  {
    id: "harbor-insurance-liam-brooks",
    cardNumber: 80,
    company: "Harbor Insurance",
    contact: "Liam Brooks",
    topic: "Contractual SLA revisions",
    owner: "Aditya Newman",
    ownerAvatar: "/avatars/aditya.jpg",
    stage: "Proposal",
    lastUpdate: "2d ago",
  },
  {
    id: "nova-manufacturing-zoe-patel",
    cardNumber: 82,
    company: "Nova Manufacturing",
    contact: "Zoe Patel",
    topic: "Factory rollout timeline and training",
    owner: "Yash Patel",
    ownerAvatar: "/avatars/yash.webp",
    stage: "Discovery",
    lastUpdate: "6h ago",
  },
  {
    id: "cedar-logistics-jason-lee",
    cardNumber: 84,
    company: "Cedar Logistics",
    contact: "Jason Lee",
    topic: "Data migration and integration plan",
    owner: "Yash Patel",
    ownerAvatar: "/avatars/yash.webp",
    stage: "Negotiation",
    lastUpdate: "8h ago",
  },
  {
    id: "brightpath-education-emma-davis",
    cardNumber: 86,
    company: "Brightpath Education",
    contact: "Emma Davis",
    topic: "Budget constraints after pilot review",
    owner: "Aditya Newman",
    ownerAvatar: "/avatars/aditya.jpg",
    stage: "Closed lost",
    lastUpdate: "1w ago",
  },
  {
    id: "pinnacle-medical-marcus-ford",
    cardNumber: 88,
    company: "Pinnacle Medical",
    contact: "Marcus Ford",
    topic: "Signature complete and onboarding prep",
    owner: "Yash Patel",
    ownerAvatar: "/avatars/yash.webp",
    stage: "Closed won",
    lastUpdate: "4d ago",
  },
  {
    id: "summit-payments-ava-morgan",
    cardNumber: 90,
    company: "Summit Payments",
    contact: "Ava Morgan",
    topic: "Legal redlines pending final approval",
    owner: "Yash Patel",
    ownerAvatar: "/avatars/yash.webp",
    stage: "Negotiation",
    lastUpdate: "3h ago",
  },
  {
    id: "orion-telecom-noah-bennett",
    cardNumber: 92,
    company: "Orion Telecom",
    contact: "Noah Bennett",
    topic: "Executive alignment on rollout phases",
    owner: "Aditya Newman",
    ownerAvatar: "/avatars/aditya.jpg",
    stage: "Proposal",
    lastUpdate: "Yesterday",
  },
];
